### ISSUE TITLE
Chain Snapshot Production Launch

### ISSUE THREAD

**Issue by stongo** [protocol/netops-guild#34]
ETA:  2022Q4
Description:
Lightweight chain snapshots are a critical part of the Filecoin network, allowing new Lotus nodes to join the network without fetching and processing the entire chain. The FIL-Infra lightweight snapshot introduces high availability and scalability, built on a flexible framework for long-term maintainability and future decentralization.

**Comment by quickhatche** [comment]
Hello! @stongo is there any status update on this? ETA says 12/2022

**Comment by stongo** [comment]
Launched!
