### ISSUE TITLE
api.chain.love Horizontal Scaling and Website

### ISSUE THREAD

**Issue by stongo** [protocol/netops-guild#35]
eta: 2022Q4
description:
A brand new logo, website and [api.chain.love](http://api.chain.love/) re-architecture, will make the Lotus Gateway better than ever. The website features an overview of use and interactive documentation, while the api.chain.love gateway service features performance and scalability improvements, and multi-region architecture.

**Comment by coryschwartz** [comment]
This can be closed, I'm pretty sure.
