### ISSUE TITLE
IPFS Gateway Saturn Integration

### ISSUE THREAD

**Issue by JesseXie** [protocol/netops-guild#47]
eta: 2023Q2
description:
More consistent and lower latency for IPFS gateways by integrating with the Saturn CDN to take advantage of the better caching that they advertise.

**Comment by momack2** [comment]
Can you rename this to "IPFS Gateway Saturn Integration" or similar please?

**Comment by quickhatche** [comment]
Hello! Checking in on the status of this - ETA shows end of Q1, should this be marked as done or status needs to be updated?

**Comment by JesseXie** [comment]
@momack2 @cewood I believe this will cross multiple quarters - I am marking it to Q2.

**Comment by quickhatche** [comment]
@JesseXie Has this milestone been completed or ETA is being updated?

**Comment by JesseXie** [comment]
@cewood I don't think Saturn can take any production traffic yet, but 30% mirror traffic is helping Saturn development.

**Comment by cewood** [comment]
We can mark this as done, we have achieved our goal for this objective; to support the IPFS Gateway integration with Saturn. As for Saturn's objective of having live traffic on Saturn by now, that was not met, no live traffic has been handled yet.
