### ISSUE TITLE
Deploy Kitsune in production

### ISSUE THREAD

**Issue by JesseXie** [protocol/netops-guild#49]
eta: 2023Q1
description:
Unlock horizontal scaling for preload nodes to maximize the utilized current instances. Bring more reliable service such as js-ipfs who is using the preload nodes.

**Comment by JesseXie** [comment]
https://blog.ipfs.tech/state-of-ipfs-in-js/#pl-delegate-and-preload-nodes-will-be-shutting-down
should we remove it instead scaling it

**Comment by BigLep** [comment]
A plan hasn't been made just for shutting down the preload nodes, but here's the tracking issue: https://github.com/ipfs/ipfs/issues/499
