### ISSUE TITLE
[General] Fil-Crypto datacenter hosts which are unresponsive

### ISSUE THREAD

**Issue by shawnrader** [protocol/netops-guild#53]
### What do you need?
The following hosts appear unresponsive to SSH connection:
worker-gpu-3 (10.2.2.28 )
worker-gpu-4 (10.2.2.27)
worker-gpu-6 (10.2.2.25)

  
### Why do you need it?
Filecoin-crypto proofs development
  
### Who is the DRI?
nemo, vmx, shawnrader, Artem, Jake

### Team and command structure
fil-crypto

### Estimated monthly cost
Systems are in-accessible by the team for development, benchmarking, and testing.
  
### What else do we need to know?
This is impairing investigation of high-priority test failure: https://github.com/filecoin-project/rust-fil-proofs/issues/1647

**Comment by coryschwartz** [comment]
I power-cycled this with IPMI.

@shawnrader you should be able to re-connect to these boxes now!
