### ISSUE TITLE
[AWS] Create `FilDev` AWS Account in Organizations

### ISSUE THREAD

**Issue by stongo** [protocol/netops-guild#55]
### What do you need?
Create a new AWS account called `FilDev` with scott.conner@protocol.ai as the initial admin 
  
### Why do you need it?
The FilDev team should have their own AWS account for creating infra resources
  
### Who is the DRI?
scott.conner@protocol.ai

### Team and command structure
LotusDev

### Estimated monthly cost
to be billed to LotusDev team's budget

**Comment by coryschwartz** [comment]
I've given access to Scott Conner for the lotus-dev-team aws account, so this can now be closed.
