### ISSUE TITLE
[General] Permission to create grafana data sources

### ISSUE THREAD

**Issue by iand** [protocol/netops-guild#57]
### What do you need?
Can you give me permission to add grafana datasources
  
### Why do you need it?
I have a project where I need to build dashboards combining data from several sources
  
### Team and command structure
Probelab

### Estimated monthly cost
nil
  
### What else do we need to know?
A crocodile cannot stick its tongue out.

**Comment by placer14** [comment]
I created a `Data Source Admin` team in Grafana and added you. Reopen if this isn't working for you.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/305332/213761766-38820c0e-fbae-4f2d-91a5-e5f0a313d9f9.png">
TIL. I had no idea. ❤️
